apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: myk0m1w5t-dotnet-basic
  janus-idp.io/tekton: myk0m1w5t-dotnet-basic
  backstage.io/kubernetes-id: myk0m1w5t-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: myk0m1w5t-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
